services:
  bookstore:
    image: bookstackapp/bookstack:latest
    container_name: bookstore
    restart: unless-stopped
    environment:
      - APP_URL=http://localhost:3002
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=bookstack
      - DB_USERNAME=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ../../data/bookstore:/config
    ports:
      - "3002:80"
    # External service dependencies (defined in services/postgres docker-compose file)
    depends_on:
      - postgres
    networks:
      - homelab
  
networks:
  homelab:
    external: true
    name: homelab
